---
title: "kags-houseprices"
output: html_notebook
---

# Loading required packages
```{r}
library(ggplot2)
library(dplyr)
library(caret)
```


# Reading in data
```{r}
data_raw <- read.csv("./Data/train.csv")
```

# Summary of data
```{r}
summary(data_raw)
```

# Removing NZV variables
```{r}
data_raw <- data_raw[, -c(1, nearZeroVar(data_raw))]
```

# Remove other unnecessary variables
```{r}
data_raw <- data_raw[, !names(data_raw) %in% c("PoolQC")]
```

# Looking at neighbourhoods
```{r}
ggplot(data_raw, aes(Neighborhood,LotArea)) + geom_boxplot() + scale_y_log10() + coord_flip()
ggplot(data_raw, aes(Neighborhood, SalePrice)) + geom_boxplot() + scale_y_log10() + coord_flip()
ggplot(data_raw, aes(log(LotArea), log(SalePrice), color = Neighborhood)) + geom_point()
with(data_raw, table(Neighborhood, BldgType))
with(data_raw, table(Neighborhood, HouseStyle))

data_raw %>% group_by(Neighborhood) %>% summarise(meanQual = mean(OverallQual, na.rm = T), meanCond = mean(OverallCond, na.rm = T)) %>% arrange(desc(meanQual))
```

Findings
Bigger lot area not always linked to higher sales price.
Overall Quality is a promising indicator of sales price. NrigdgeHeights best quality.

```{r}

```

